accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),

]

market/urls.py
from django.urls import path
from market import views

app_name = 'market'
urlpatterns = [
    path("", views.index_page, name='index'),
    path("createseller/", views.create_seller, name='create_seller'),
    path("createproduct/", views.create_product, name='create_product'),
    path("table_view/", views.TableView.as_view(), name='table_view'),
    path("sellers/", views.SellerView.as_view(), name='sellers'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('product_data_update/<int:product_id>/', views.product_data_update, name='product_data_update'),
]

meli/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('market.urls')),
]

market/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.core.mail import send_mail


class Seller(models.Model):
    supervisor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='supervisor')
    nickname = models.CharField(max_length=45, unique=True)
    phone = PhoneNumberField()
    email = models.EmailField(max_length=30, unique=True)
    

    def __str__(self):
        return self.nickname

class Product(models.Model):
    seller_fk = models.ForeignKey(Seller, on_delete=models.CASCADE, 
                                  related_name="seller_fk")
    title = models.CharField(max_length=80)
    product_id = models.CharField(max_length=30)
    sellerid = models.CharField(max_length=30, null=True)
    brand = models.CharField(max_length=30)
    ppv = models.IntegerField()
    brand_discount_allow = models.FloatField(default=0)
    base_price = models.IntegerField(null=True)
    original_price = models.IntegerField(null=True)
    discount_ammount = models.IntegerField(null=True)
    discount_percent = models.FloatField(null=True)
    fault_date = models.DateTimeField(blank=True, null=True)    
    created = models.DateTimeField(auto_now_add = True)
    modified = models.DateTimeField(auto_now = True)
    
    
    def raise_alert(self):
        return self.discount_percent > self.brand_discount_allow or self.ppv > self.base_price 
    
    def email_notify(self):
        if self.raise_alert() and self.fault_date is None:
            self.fault_date = timezone.now()
            self.save()
            seller_email = self.seller_fk.email
            supervisor_email = self.seller_fk.supervisor.email
            subject = f'Precio fuera del rango permitido - Artículo {self.product_id}'
            message = f"El artículo: '{self.title}', cuyo PVP es ${self.ppv}, posee un precio publicado de ${self.base_price}. Favor de corregir."
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [seller_email, supervisor_email, ]
            if send_mail( subject, message, email_from, recipient_list ):
                print(f'Mail was Send to {seller_email} and {supervisor_email}')
            else:
                print('Error with the send of the mail')
        print('The user was notified or is not necessarily.')
    
    def __str__(self):
        return self.title

market/forms.py
from django import forms
from .models import Seller, Product
from django.utils.translation import gettext_lazy as _


    
class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].required = False
        self.fields['brand'].required = False
        if self.instance and self.instance.pk:
            self.fields.pop('product_id', None)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'
            
    class Meta:
        model = Product
        fields = ['seller_fk', 'title' , 'product_id', 'brand', 'ppv', 'brand_discount_allow']
        exclude = ['seller_id', 'original_price', 'base_price', 'discount_ammount',
                   'discount_percent', 'alert']
        labels = {
            'seller_fk': _('Vendedor'),
            'product_id': _('ProductID'),
            'ppv': _('PPV'),
            'title': _('Nombre del Producto'),
            'brand': _('Marca del Producto'),
            'brand_discount_allow': _('Descuento Permitido por la Marca(%)')
        }
        
class SellerForm(forms.ModelForm): 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Seller
        fields = "__all__"
        labels = {
                'nickname': _('Nickname del Vendedor o ID de vendedor de MELI'),
                'phone': _('Número de Celular o Teléfono (con extensión)'),
                }        
        

market/views.py
from market.functions import product_details, update_product_data
from django.views import generic
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .forms import SellerForm, ProductForm
from .models import Product, Seller
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index_page(request):
    return render(request, 'market/index.html', {})

@login_required
def create_seller(request):
	if request.method == "POST":
		seller_form = SellerForm(request.POST)
		if seller_form.is_valid():
			seller_form.save()
			messages.success(request, ('El vendedor fue creado exitosamente!'))
		else:
			messages.error(request, 'Ups! Al parecer hubo un error con el llenado del formulario. Verifique introducir datos válidos.')
		return redirect(reverse("market:index"))
	seller_form = SellerForm()
	return render(request=request, template_name="market/create_seller.html", context={'seller_form':seller_form})


class TableView(generic.ListView):
    template_name = 'market/table.html'
    queryset = Product.objects.all()
    context_object_name = 'items_data'
    
    def dispatch(self, request, *args, **kwargs):
        if len(self.queryset) >= 1:
            for obj in self.queryset:
                obj.email_notify()     
        return super().dispatch(request, *args, **kwargs)
    
class SellerView(generic.ListView):
    template_name = 'market/sellers.html'
    context_object_name = 'seller_data'
    queryset = Seller.objects.all()


@login_required
def create_product(request):
	if request.method == "POST":
		product_form = ProductForm(request.POST)
		item_value = product_form['product_id'].value()
		item_title = product_form['title'].value()
		item_brand = product_form['brand'].value()
		item_details = product_details(item_value)
		if item_details and product_form.is_valid():
			product = product_form.save(commit=False)
			product.title = item_details[0]['title'] if item_title is not None else item_title
			product.brand = item_details[0]['brand'] if item_brand is not None else item_brand
			product.sellerid = item_details[0]['seller_id']
			product.base_price = item_details[0]['base_price']
			product.original_price = item_details[0]['original_price']
			product.discount_ammount = item_details[0]['discount_ammount']
			product.discount_percent = item_details[0]['discount_percent']
			product.brand_discount_allow = product_form['brand_discount_allow'].value()
			product.save()
			messages.success(request, ('Su producto fue añadido exitosamente!'))
			return redirect(reverse("market:table_view"))
		else:
			messages.error(request, 'Ups! Hubo un error con sus datos en el formulario, verifique que el product_id sea correcto.')
	product_form = ProductForm()
	return render(request=request, template_name="market/create_product.html", context={'product_form':product_form})
    
@login_required
def update_product(request, product_id):
    obj = get_object_or_404(Product, pk=product_id)
    if request.method == "POST" and obj:
        product_form = ProductForm(request.POST or None, instance = obj)
        if product_form.is_valid():
            product_form.save()
            messages.success(request, ('Su producto fue editado exitosamente!'))
            return redirect(reverse("market:table_view"))
        else:
            messages.error(request, 'Ups! Al parecer hubo un error con el llenado del formulario.')
    else:
        product_form = ProductForm(instance=obj)
    return render(request=request, template_name="market/edit_product.html", context={'product_form':product_form})

@login_required
def delete_product(request, product_id):
    obj = get_object_or_404(Product, pk=product_id)
    obj.delete()
    messages.warning(request, "Producto eliminado.")
    return redirect(reverse("market:table_view"))

@login_required
def product_data_update(request, product_id):
    obj = get_object_or_404(Product, pk=product_id)
    update_product_data(obj, product_details(obj.product_id))
    messages.info(request, "Datos del producto actualizado.")
    return redirect(reverse("market:table_view"))

market/templates/market/base.html
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
      <title>{% block title %}{% endblock %}</title>
   </head>
   <body>
    <header>
      {% load static %}
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">

        <a class="navbar-brand mx-3"  style="font-size:13px; font-style: italic;" href="{% url 'market:index' %}">
          <img src="{% static 'img/br_pr.png' %}" width="150"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'market:create_product' %}">Crear Producto<span class="sr-only"></span></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'market:create_seller' %}">Crear Vendedor</a>
              </li>
          </ul>
            {% if user.is_authenticated %}
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'market:table_view'%}">Productos</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:logout_user'%}">Cerrar Sesión</a>
                  </li>
              </ul>
            {% else %}
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:login_user' %}">Iniciar Sesión</a>
                  </li>
              </ul>
            {% endif %}
        </div>
      </nav>
    </header>
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}

    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

market/templates/market/create_product.html
{% extends 'market/base.html' %}
{% block title %}Create Product{% endblock %}
{% block content %}

{% load crispy_forms_tags %}  

  <div class="container">
    <h2 class="my-4 text-center">Add a new product</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
          {{product_form|crispy}}
          <button class="btn btn-primary my-4" type="submit">Submit</button>
    </form>
  </div>
{% endblock %}

market/templates/market/create_seller.html
{% extends 'market/base.html' %}
{% block title %}Create Seller{% endblock %}
{% block content %}

{% load crispy_forms_tags %}  
  
  <div class="container">
    <h2 class="my-4 text-center">Add a new seller</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
          {{seller_form|crispy}}
          <button class="btn btn-primary my-4" type="submit">Submit</button>
    </form>
  </div>
{% endblock %}

market/templates/market/edit_product.html
{% extends 'market/base.html' %}
{% block title %}Edit Product{% endblock %}
{% block content %}

{% load crispy_forms_tags %}  

  <div class="container">
    <h2 class="my-4 text-center">Edit an existing product</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
          {{product_form|crispy}}
          <button class="btn btn-primary my-4" type="submit">Submit</button>
    </form>
  </div>
{% endblock %}

market/templates/market/index.html
{% extends 'market/base.html' %}
{% block title %}Home Page{% endblock %}
{% block content %}
<div class="card">
  <br>
  <h3 class="card-title text-center">Productos y Vendedores</h3>
  <div class="card-body">
      <br>
      <h5 class='text-left'>Bienvenido Supervisor: {{user.username}}</h5>
      <div class="list-group">
        <a href="{% url 'market:sellers'%}" class="list-group-item list-group-item-action">Lista de los Vendedores</a>
        <a href="{% url 'market:table_view' %}" class="list-group-item list-group-item-action">Lista de los Productos</a>
      </div>
      <div class="text-center p-4" style="   width: 100% !important; margin-top:8.3rem; ">
          Copyright © Brandproteccion 2022
      </div>
    </div>

{% endblock %}

market/templates/market/sellers.html
{% extends 'market/base.html' %}
{% block title %}Seller Table{% endblock %}
{% block content %}
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Manager</th>
      <th scope="col">Nickname</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    {% for seller in seller_data %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{seller.supervisor}}</td>
        <td>{{seller.nickname}}</td>
        <td>{{seller.phone}}</td>
        <td>{{seller.email}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

market/templates/market/table.html
{% extends 'market/base.html' %}
{% block title %}Product Table{% endblock %}
{% block content %}
<div class="container-fluids">
  <table border="2" class="table table-bordered table-striped table-hover">
    <thead style="color:white; background:gray; text-align:center;">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Vendedor</th>
        <th scope="col">Vendedor ID</th>
        <th scope="col">Título</th>
        <th scope="col">Marca</th>
        <th scope="col">Producto ID</th>
        <th scope="col">Precio Original</th>
        <th scope="col">Precio Base</th>
        <th scope="col">PPV</th>
        <th scope="col">Descuento</th>
        <th scope="col">Descuento en Porcentaje(%)</th>
        <th scope="col">Descuento Permitido por la Marca(%)</th>
        <th scope="col">Alertas</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody style=" text-align:center; color:white; background:gray;">
      {% for item in items_data %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{item.seller_fk}}</td>
          <td>{{item.sellerid}}</td>
          <td>{{item.title}}</td>
          <td>{{item.brand}}</td>
          <td>{{item.product_id}}</td>
          <td>{{item.original_price}}</td>
          <td>{{item.base_price}}</td>
          <td>{{item.ppv}}</td>
          <td>{{item.discount_ammount}}</td>
          <td>{{item.discount_percent}}</td>
          <td>{{item.brand_discount_allow}}</td>
          {% if item.raise_alert %}
            <td class="table-danger">Esta por encima del permitido</td>
          {% else %}
            <td class="table-info">Esta por debajo del permitido</td>
          {% endif %}
          <td>
            <div class="btn-group">
              <a class="btn btn-primary" href="{% url 'market:update_product' item.id %}">
                Editar
              </a>
              <a class="btn btn-danger" href="{% url 'market:delete_product' item.id %}">
                Borrar
              </a>
              <a class="btn btn-info" href="{% url 'market:product_data_update' item.id %}">
                Actualizar
              </a>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}